### ISSUE TITLE
Some syntax not supported

### ISSUE THREAD

**Issue by alecthomas** [sylver-dev/golang#1]
First off, sylver looks really promising. Love the concept.

I ran it on [chroma](https://github.com/alecthomas/chroma) and it fails on hex literals:

```
error[Unexpected token: IDENTIFIER_CONTENT, expected: \}, ,]: Unexpected IDENTIFIER_CONTENT
   ┌─ style_test.go:15:38
   │
15 │     assert.Equal(t, StyleEntry{Colour: 0x1000000, Bold: Yes}, s.Get(NameVariable))
   │                                         ^^^^^^^^
```

I ran it on another project that uses generics and it also seems to fail on those.

**Comment by geoffreycopin** [comment]
Thanks for your kind word !

The spec now includes hexadecimal/octal/binary numbers and type arguments in calls. There is no more parsing error 
on https://github.com/alecthomas/chroma. To use the updated spec, you'll have to delete your `.sylver` directory (at the root of your project, if that's where you ran `sylver rulset run`).

Don't hesitate to let me know if you have further issues.

**Comment by alecthomas** [comment]
Nice, this works for me now, thank you!
